version: '3.7'
services:
  client:
    build:
      context: .
      target: base
    volumes:
      - ./node_modules:/app/node_modules
      - .:/app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
    # links:
    #   - graphql
